JSON_STRING :: #string DONE
{
    "asset": {
        "generator": "FBX2glTF v0.13.0",
        "version": "2.0"
    },
    "scene": 0,
    "buffers": [
        {
            "byteLength": 12182680,
            "uri": "buffer.bin"
        }
    ],
    "bufferViews": [
        {
            "buffer": 0,
            "byteLength": 155322,
            "byteOffset": 0,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 673416,
            "byteOffset": 155324,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 673416,
            "byteOffset": 828740,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 448944,
            "byteOffset": 1502156,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 393900,
            "byteOffset": 1951100,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 795252,
            "byteOffset": 2345000,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 795252,
            "byteOffset": 3140252,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 530168,
            "byteOffset": 3935504,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 393900,
            "byteOffset": 4465672,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 795360,
            "byteOffset": 4859572,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 795360,
            "byteOffset": 5654932,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 530240,
            "byteOffset": 6450292,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 140892,
            "byteOffset": 6980532,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 543768,
            "byteOffset": 7121424,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 543768,
            "byteOffset": 7665192,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 362512,
            "byteOffset": 8208960,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 101334,
            "byteOffset": 8571472,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 391620,
            "byteOffset": 8672808,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 391620,
            "byteOffset": 9064428,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 261080,
            "byteOffset": 9456048,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 113202,
            "byteOffset": 9717128,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 436896,
            "byteOffset": 9830332,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 436896,
            "byteOffset": 10267228,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 291264,
            "byteOffset": 10704124,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 7260,
            "byteOffset": 10995388,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 29352,
            "byteOffset": 11002648,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 29352,
            "byteOffset": 11032000,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 19568,
            "byteOffset": 11061352,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 7260,
            "byteOffset": 11080920,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 29244,
            "byteOffset": 11088180,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 29244,
            "byteOffset": 11117424,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 19496,
            "byteOffset": 11146668,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 7260,
            "byteOffset": 11166164,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 29328,
            "byteOffset": 11173424,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 29328,
            "byteOffset": 11202752,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 19552,
            "byteOffset": 11232080,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 7776,
            "byteOffset": 11251632,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 32412,
            "byteOffset": 11259408,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 32412,
            "byteOffset": 11291820,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 21608,
            "byteOffset": 11324232,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 7776,
            "byteOffset": 11345840,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 32268,
            "byteOffset": 11353616,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 32268,
            "byteOffset": 11385884,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 21512,
            "byteOffset": 11418152,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 7710,
            "byteOffset": 11439664,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 31668,
            "byteOffset": 11447376,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 31668,
            "byteOffset": 11479044,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 21112,
            "byteOffset": 11510712,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 7710,
            "byteOffset": 11531824,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 31632,
            "byteOffset": 11539536,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 31632,
            "byteOffset": 11571168,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 21088,
            "byteOffset": 11602800,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 4632,
            "byteOffset": 11623888,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 18528,
            "byteOffset": 11628520,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 18528,
            "byteOffset": 11647048,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 12352,
            "byteOffset": 11665576,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 3792,
            "byteOffset": 11677928,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 15288,
            "byteOffset": 11681720,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 15288,
            "byteOffset": 11697008,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 10192,
            "byteOffset": 11712296,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 39576,
            "byteOffset": 11722488,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 157368,
            "byteOffset": 11762064,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 157368,
            "byteOffset": 11919432,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 104912,
            "byteOffset": 12076800,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 72,
            "byteOffset": 12181712,
            "target": 34963
        },
        {
            "buffer": 0,
            "byteLength": 336,
            "byteOffset": 12181784,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 336,
            "byteOffset": 12182120,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 224,
            "byteOffset": 12182456,
            "target": 34962
        }
    ],
    "scenes": [
        {
            "name": "Root Scene",
            "nodes": [
                0
            ]
        }
    ],
    "accessors": [
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 77661,
            "bufferView": 0,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 56118,
            "bufferView": 1,
            "byteOffset": 0,
            "min": [
                0.11540075391531,
                -0.0257798787206411,
                -0.219031468033791
            ],
            "max": [
                0.216260746121407,
                0.1091173812747,
                -0.122352823615074
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 56118,
            "bufferView": 2,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 56118,
            "bufferView": 3,
            "byteOffset": 0
        },
        {
            "componentType": 5125,
            "type": "SCALAR",
            "count": 98475,
            "bufferView": 4,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 66271,
            "bufferView": 5,
            "byteOffset": 0,
            "min": [
                0.119928687810898,
                6.12999974691775e-06,
                0.115426525473595
            ],
            "max": [
                0.209820508956909,
                0.214620754122734,
                0.209241569042206
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 66271,
            "bufferView": 6,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 66271,
            "bufferView": 7,
            "byteOffset": 0
        },
        {
            "componentType": 5125,
            "type": "SCALAR",
            "count": 98475,
            "bufferView": 8,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 66280,
            "bufferView": 9,
            "byteOffset": 0,
            "min": [
                -0.209366753697395,
                6.12999974691775e-06,
                0.115426525473595
            ],
            "max": [
                -0.119474932551384,
                0.214620754122734,
                0.209241569042206
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 66280,
            "bufferView": 10,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 66280,
            "bufferView": 11,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 70446,
            "bufferView": 12,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 45314,
            "bufferView": 13,
            "byteOffset": 0,
            "min": [
                0.00160161999519914,
                -0.00887036975473166,
                -0.207840844988823
            ],
            "max": [
                0.114236153662205,
                0.134946033358574,
                -0.0970795452594757
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 45314,
            "bufferView": 14,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 45314,
            "bufferView": 15,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 50667,
            "bufferView": 16,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 32635,
            "bufferView": 17,
            "byteOffset": 0,
            "min": [
                -0.0846045985817909,
                -0.0208955686539412,
                -0.205037906765938
            ],
            "max": [
                8.20599962025881e-05,
                0.0881790742278099,
                -0.117252841591835
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 32635,
            "bufferView": 18,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 32635,
            "bufferView": 19,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 56601,
            "bufferView": 20,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 36408,
            "bufferView": 21,
            "byteOffset": 0,
            "min": [
                -0.199848115444183,
                -0.0251208078116179,
                -0.225719749927521
            ],
            "max": [
                -0.0873213484883308,
                0.0839538276195526,
                -0.121155261993408
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 36408,
            "bufferView": 22,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 36408,
            "bufferView": 23,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 3630,
            "bufferView": 24,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2446,
            "bufferView": 25,
            "byteOffset": 0,
            "min": [
                -0.0982124954462051,
                0.00135362998116761,
                0.0575526617467403
            ],
            "max": [
                -0.0536653809249401,
                0.0300101898610592,
                0.104291468858719
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2446,
            "bufferView": 26,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 2446,
            "bufferView": 27,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 3630,
            "bufferView": 28,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2437,
            "bufferView": 29,
            "byteOffset": 0,
            "min": [
                -0.0401365086436272,
                0.00113489001523703,
                -0.0735023319721222
            ],
            "max": [
                0.00232395995408297,
                0.029791459441185,
                -0.049265880137682
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2437,
            "bufferView": 30,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 2437,
            "bufferView": 31,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 3630,
            "bufferView": 32,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2444,
            "bufferView": 33,
            "byteOffset": 0,
            "min": [
                0.0431076884269714,
                0.0011504499707371,
                0.0756991803646088
            ],
            "max": [
                0.087575264275074,
                0.0298070311546326,
                0.122444093227386
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2444,
            "bufferView": 34,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 2444,
            "bufferView": 35,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 3888,
            "bufferView": 36,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2701,
            "bufferView": 37,
            "byteOffset": 0,
            "min": [
                0.0580754280090332,
                0.000868130009621382,
                -0.0344349592924118
            ],
            "max": [
                0.14180526137352,
                0.0837612003087997,
                0.049008309841156
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2701,
            "bufferView": 38,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 2701,
            "bufferView": 39,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 3888,
            "bufferView": 40,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2689,
            "bufferView": 41,
            "byteOffset": 0,
            "min": [
                -0.106807753443718,
                0.000999990035779774,
                0.00885386951267719
            ],
            "max": [
                -0.0746670737862587,
                0.042446531355381,
                0.0409328974783421
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2689,
            "bufferView": 42,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 2689,
            "bufferView": 43,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 3855,
            "bufferView": 44,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2639,
            "bufferView": 45,
            "byteOffset": 0,
            "min": [
                0.0240564290434122,
                7.92299906606786e-05,
                -0.0772491469979286
            ],
            "max": [
                0.0685899406671524,
                0.0415257588028908,
                -0.0327156409621239
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2639,
            "bufferView": 46,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 2639,
            "bufferView": 47,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 3855,
            "bufferView": 48,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2636,
            "bufferView": 49,
            "byteOffset": 0,
            "min": [
                0.000874319928698242,
                -0.000744210032280535,
                0.10929499566555
            ],
            "max": [
                0.0333806276321411,
                0.0407023169100285,
                0.141801297664642
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 2636,
            "bufferView": 50,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 2636,
            "bufferView": 51,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 2316,
            "bufferView": 52,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 1544,
            "bufferView": 53,
            "byteOffset": 0,
            "min": [
                -0.0896041095256805,
                -0.000147629994899035,
                -0.0500704608857632
            ],
            "max": [
                -0.0497355684638023,
                0.0326878577470779,
                -0.00298585998825729
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 1544,
            "bufferView": 54,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 1544,
            "bufferView": 55,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 1896,
            "bufferView": 56,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 1274,
            "bufferView": 57,
            "byteOffset": 0,
            "min": [
                -0.0620503351092339,
                0.000757439993321896,
                0.0900291875004768
            ],
            "max": [
                -0.0120056699961424,
                0.0311571899801493,
                0.136791735887527
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 1274,
            "bufferView": 58,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 1274,
            "bufferView": 59,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 19788,
            "bufferView": 60,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 13114,
            "bufferView": 61,
            "byteOffset": 0,
            "min": [
                -0.0252518504858017,
                -0.0136416396126151,
                0.00332015007734299
            ],
            "max": [
                0.0446008369326591,
                0.162037432193756,
                0.0683249980211258
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 13114,
            "bufferView": 62,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 13114,
            "bufferView": 63,
            "byteOffset": 0
        },
        {
            "componentType": 5123,
            "type": "SCALAR",
            "count": 36,
            "bufferView": 64,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 28,
            "bufferView": 65,
            "byteOffset": 0,
            "min": [
                -0.199999988079071,
                -0.0621090866625309,
                -0.199999988079071
            ],
            "max": [
                0.199999988079071,
                0.000866840011440217,
                0.199999988079071
            ]
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 28,
            "bufferView": 66,
            "byteOffset": 0
        },
        {
            "componentType": 5126,
            "type": "VEC2",
            "count": 28,
            "bufferView": 67,
            "byteOffset": 0
        }
    ],
    "images": [
        {
            "name": "sample_town.png",
            "uri": "sample_town.png"
        }
    ],
    "samplers": [
        {}
    ],
    "textures": [
        {
            "name": "base_color_texture",
            "sampler": 0,
            "source": 0
        }
    ],
    "materials": [
        {
            "name": "Material.002",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorFactor": [
                    0.800000011920929,
                    0.800000011920929,
                    0.800000011920929,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "PolygonCastle_Texture_01_A",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "PolygonCastle_Texture_01_A41",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "PolygonCastle_Texture_01_A41.001",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "PolygonCastle_Texture_01_A1.001",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "PolygonCastle_Texture_01_A20",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "PolygonCastle_Texture_01_A2",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "lambert1612",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "lambert1618",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "lambert1615",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "lambert1695",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "lambert1691",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "lambert1697",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "lambert1689",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "lambert1619",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "lambert1703",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        },
        {
            "name": "lambert1850",
            "alphaMode": "OPAQUE",
            "doubleSided": false,
            "extras": {
                "fromFBX": {
                    "shadingModel": "Phong",
                    "isTruePBR": false
                }
            },
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0,
                    "texCoord": 0
                },
                "baseColorFactor": [
                    1.0,
                    1.0,
                    1.0,
                    1.0
                ],
                "metallicFactor": 0.400000005960464,
                "roughnessFactor": 0.272165536880493
            }
        }
    ],
    "meshes": [
        {
            "name": "SM_Bld_Preset_House_01_A_Optimized_Mesh",
            "primitives": [
                {
                    "material": 1,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 2,
                        "POSITION": 1,
                        "TEXCOORD_0": 3
                    },
                    "indices": 0
                }
            ]
        },
        {
            "name": "SM_Bld_Preset_Tower_01_Optimized_Mesh.001",
            "primitives": [
                {
                    "material": 2,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 6,
                        "POSITION": 5,
                        "TEXCOORD_0": 7
                    },
                    "indices": 4
                }
            ]
        },
        {
            "name": "SM_Bld_Preset_Tower_01_Optimized.001_Mesh.002",
            "primitives": [
                {
                    "material": 3,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 10,
                        "POSITION": 9,
                        "TEXCOORD_0": 11
                    },
                    "indices": 8
                }
            ]
        },
        {
            "name": "SM_Bld_Preset_House_05_Optimized_Mesh.004",
            "primitives": [
                {
                    "material": 4,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 14,
                        "POSITION": 13,
                        "TEXCOORD_0": 15
                    },
                    "indices": 12
                }
            ]
        },
        {
            "name": "SM_Bld_Preset_House_09_B_Optimized_Mesh.005",
            "primitives": [
                {
                    "material": 5,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 18,
                        "POSITION": 17,
                        "TEXCOORD_0": 19
                    },
                    "indices": 16
                }
            ]
        },
        {
            "name": "SM_Bld_Preset_House_07_Optimized_Mesh.006",
            "primitives": [
                {
                    "material": 6,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 22,
                        "POSITION": 21,
                        "TEXCOORD_0": 23
                    },
                    "indices": 20
                }
            ]
        },
        {
            "name": "SM_Prop_Market_Stall_01_Mesh.007",
            "primitives": [
                {
                    "material": 7,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 26,
                        "POSITION": 25,
                        "TEXCOORD_0": 27
                    },
                    "indices": 24
                }
            ]
        },
        {
            "name": "SM_Prop_Market_Stall_07_Mesh.008",
            "primitives": [
                {
                    "material": 8,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 30,
                        "POSITION": 29,
                        "TEXCOORD_0": 31
                    },
                    "indices": 28
                }
            ]
        },
        {
            "name": "SM_Prop_Market_Stall_04_Mesh.009",
            "primitives": [
                {
                    "material": 9,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 34,
                        "POSITION": 33,
                        "TEXCOORD_0": 35
                    },
                    "indices": 32
                }
            ]
        },
        {
            "name": "SM_Prop_Market_Stall_05_Mesh.010",
            "primitives": [
                {
                    "material": 10,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 38,
                        "POSITION": 37,
                        "TEXCOORD_0": 39
                    },
                    "indices": 36
                }
            ]
        },
        {
            "name": "SM_Prop_Market_Stall_03_Mesh.011",
            "primitives": [
                {
                    "material": 11,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 42,
                        "POSITION": 41,
                        "TEXCOORD_0": 43
                    },
                    "indices": 40
                }
            ]
        },
        {
            "name": "SM_Prop_Market_Stall_06_Mesh.012",
            "primitives": [
                {
                    "material": 12,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 46,
                        "POSITION": 45,
                        "TEXCOORD_0": 47
                    },
                    "indices": 44
                }
            ]
        },
        {
            "name": "SM_Prop_Market_Stall_02_Mesh.013",
            "primitives": [
                {
                    "material": 13,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 50,
                        "POSITION": 49,
                        "TEXCOORD_0": 51
                    },
                    "indices": 48
                }
            ]
        },
        {
            "name": "SM_Prop_Market_Stall_08_Mesh.014",
            "primitives": [
                {
                    "material": 14,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 54,
                        "POSITION": 53,
                        "TEXCOORD_0": 55
                    },
                    "indices": 52
                }
            ]
        },
        {
            "name": "SM_Prop_Market_Stall_09_Mesh.015",
            "primitives": [
                {
                    "material": 15,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 58,
                        "POSITION": 57,
                        "TEXCOORD_0": 59
                    },
                    "indices": 56
                }
            ]
        },
        {
            "name": "SM_Prop_Statue_Hero_01_Mesh.016",
            "primitives": [
                {
                    "material": 16,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 62,
                        "POSITION": 61,
                        "TEXCOORD_0": 63
                    },
                    "indices": 60
                }
            ]
        },
        {
            "name": "Cube_Cube.002",
            "primitives": [
                {
                    "material": 0,
                    "mode": 4,
                    "attributes": {
                        "NORMAL": 66,
                        "POSITION": 65,
                        "TEXCOORD_0": 67
                    },
                    "indices": 64
                }
            ]
        }
    ],
    "nodes": [
        {
            "name": "RootNode",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                0.0,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                1.0,
                1.0,
                1.0
            ],
            "children": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17
            ]
        },
        {
            "name": "Cube_Cube.002",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 16
        },
        {
            "name": "SM_Bld_Preset_House_01_A_Optimized_Mesh",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 0
        },
        {
            "name": "SM_Bld_Preset_Tower_01_Optimized_Mesh.001",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 1
        },
        {
            "name": "SM_Bld_Preset_Tower_01_Optimized.001_Mesh.002",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 2
        },
        {
            "name": "SM_Bld_Preset_House_05_Optimized_Mesh.004",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 3
        },
        {
            "name": "SM_Bld_Preset_House_09_B_Optimized_Mesh.005",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 4
        },
        {
            "name": "SM_Bld_Preset_House_07_Optimized_Mesh.006",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 5
        },
        {
            "name": "SM_Prop_Market_Stall_01_Mesh.007",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 6
        },
        {
            "name": "SM_Prop_Market_Stall_07_Mesh.008",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 7
        },
        {
            "name": "SM_Prop_Market_Stall_04_Mesh.009",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 8
        },
        {
            "name": "SM_Prop_Market_Stall_05_Mesh.010",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 9
        },
        {
            "name": "SM_Prop_Market_Stall_03_Mesh.011",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 10
        },
        {
            "name": "SM_Prop_Market_Stall_06_Mesh.012",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 11
        },
        {
            "name": "SM_Prop_Market_Stall_02_Mesh.013",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 12
        },
        {
            "name": "SM_Prop_Market_Stall_08_Mesh.014",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 13
        },
        {
            "name": "SM_Prop_Market_Stall_09_Mesh.015",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 14
        },
        {
            "name": "SM_Prop_Statue_Hero_01_Mesh.016",
            "translation": [
                0.0,
                0.0,
                0.0
            ],
            "rotation": [
                8.14603353660459e-08,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                100.0,
                100.0,
                100.0
            ],
            "mesh": 15
        }
    ]
}
DONE

JsonType :: struct {
    asset: GltfJsonAsset;
    scene: int;
    buffers: [..] GltfJsonBuffer;
    bufferViews: [..] GltfJsonBufferView;
    scenes: [..] GltfJsonScene;
    accessors: [..] GltfJsonAccessor;
    images: [..] GltfJsonImage;
    samplers: [..] GltfJsonSampler;
    textures: [..] GltfJsonTexture;
    materials: [..] GltfJsonMaterial;
    meshes: [..] GltfJsonMesh;
    nodes: [..] GltfJsonNode;

    GltfJsonAsset :: struct {
        copyright: *string;
        generator: *string;
        version: string;
        minVersion: *string;
    }

    GltfJsonBuffer :: struct {
        uri: *string;
        byteLength: int;
        name: *string;
    }

    GltfJsonBufferView :: struct {
        buffer: int;
        byteOffset: int = 0;
        byteLength: int;
        byteStride: *int;
        target: *int;
        name: *string;
    }

    GltfJsonScene :: struct {
        nodes: *[..] int;
        name: *string;
    }

    GltfJsonAccessor :: struct {
        bufferView: *int;
        byteOffset: int = 0;
        componentType: int;
        normalized: bool = false;
        count: int;
        type: string;
        max: *[..] float64;
        min: *[..] float64;
        sparse: *struct {
            count: int;
            indices: struct {
                bufferView: int;
                byteOffset: int = 0;
                componentType: int;
            };
            values: struct {
                bufferView: int;
                byteOffset: int = 0;
            };
        };
        name: *string;
    }

    GltfJsonImage :: struct {
        uri: *string;
        mimeType: *string;
        bufferView: *int;
        name: *string;
    }

    GltfJsonSampler :: struct {
        magFilter: *int;
        minFilter: *int;
        wrapS: int = 0x2901;
        wrapT: int = 0x2901;
        name: *string;
    }

    GltfJsonTexture :: struct {
        sampler: *int;
        source: *int;
        name: *string;
    }

    GltfJsonMaterial :: struct {
        name: *string;
        pbrMetallicRoughness: *struct {
            baseColorFactor: [4] float64 = .[1, 1, 1, 1];
            baseColorTexture: *struct {
                index: int;
                texCoord: int = 0;
            };
            metallicFactor: float64 = 1.0;
            roughnessFactor: float64 = 1.0;
            metallicRoughnessTexture: *struct {
                index: int;
                texCoord: int = 0;
            };
        };
        normalTexture: *struct {
            index: int;
            texCoord: int = 0;
            scale: float64 = 1.0;
        };
        occlusionTexture: *struct {
            index: int;
            texCoord: int = 0;
            strength: float64 = 1.0;
        };
        emissiveTexture: *struct {
            index: int;
            texCoord: int = 0;
        };
        emissiveFactor: [3] float64 = .[0, 0, 0];
        alphaMode: string = "OPAQUE";
        alphaCutoff: float64 = 0.5;
        doubleSided: bool = false;
    }

    GltfJsonMesh :: struct {
        primitives: [..] struct {
            // attributes: JsonObject; TODO
            indices: *int;
            material: *int;
            mode: int = 4;
            // targets: [..] JsonObject; // TODO morph targets
        };
        weights: [..] float64;
        name: string;
    }

    GltfJsonNode :: struct {
        camera: *int;
        children: *[..] int;
        skin: *int;
        matrix: [16] float64 = .[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];
        mesh: *int;
        rotation: [4] float64 = .[0, 0, 0, 1];
        scale: [3] float64 = .[1, 1, 1];
        translation: [3] float64 = .[0, 0, 0];
        weights: *[..] float64;
        name: *string;
    }
}